### ISSUE TITLE
The REQUIREMENTS.md should be a plain text file

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#316]
The REQUIREMENTS.md file should be requirements.txt with just a plain list of the requirements as it needs to work with pip install. requirements.txt should only include pip installable requirements and can't have text in it. Also some of the packages listed are not required directly by pymks, but are installed as part of other packages. Requirements for reading and instruction should go in the installation instructions.

**Comment by tushar-rishav** [comment]
@wd15 I faced the same problem and was about to fine an exact same issue. It's really annoying to install dependencies manually. Maybe it'd be nice to load the requirements (using `install_requires`) into setup.py itself?  Here is a prototype
```python
with open('requirements.txt') as requirements:
    required = requirements.read().splitlines()

setup(name='pymks',
      version=getVersion('0.3.1', release=True),
      install_requires=required
      ...)
```
Thoughts?

**Comment by wd15** [comment]
@tushar-rishav, what you suggested is great. Perhaps do not specify the version numbers but let's ensure that the tests on travis uses the requirements.txt. At the moment the conda install of the requirements for pymks is used (see https://github.com/materialsinnovation/pymks/blob/master/.travis.yml). We can still use a conda environment for the tests, but let's just let the `pip install .` take care of the prerequisites. Obviously, sfepy and pyfftw shouldn't be in requirements.txt, I don't think they are pip installable.

**Comment by tushar-rishav** [comment]
@wd15 Unfortunately, I am not comfortable with conda yet. :sweat_smile: 

____________
>let's ensure that the tests on travis uses the requirements.txt.

Including packages in setup.py from `requirements.txt` will ensure that at least python packages are installed when user runs installs from PyPi or  from source. If none of those, then just install separately by `pip install -r requirements.txt`. Either way, it works.


>Obviously, sfepy and pyfftw shouldn't be in requirements.txt, I don't think they are pip installable.
True. I think for the sake of tests at travis, we may install them separately. That'd require creating a shell script for installation otherwise just dump those installation command in `travis.yml`. Either way it should do the job. I guess travis runs Ubuntu.

**Comment by tushar-rishav** [comment]
@wd15 Also, IIRC versions are required for packaging. The proposed change will just add `install_requires=required` and load requirements in `required`.

**Comment by wd15** [comment]
This issue has been fixed.
