### ISSUE TITLE
The domain argument in basis functions should really be range

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#327]
Domain is associated with spatial regions. State space should be referred to as a range. A user reported to me that this caused a lot of confusion when debugging in a code that uses PyMKS.

**Comment by davidbrough1** [comment]
There are cases with the spectral bases it is useful to only include the most dominate the local states instead of a range. This is especially true for the `GSHBasis` class where the contribution from most of the influence coefficients is negligible as demonstrated in [the polycrystal example](http://pymks.org/en/latest/rst/notebooks/localization_elasticity_polycrystal_hex_3D.html).

**Comment by wd15** [comment]
@davidbrough1, basically, what you are saying is that there is a valid reason to call the argument "domain" as opposed to "range"?
