### ISSUE TITLE
Remove the develop branch after 0.4 release

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#405]

**Comment by beyucel** [comment]
Hey, All (@wd15  and @auag92). I think this is our priority for moving forward. I feel like once we are done with # 421, all notebooks will be ready for the next release. I think we need to do the next release as soon as possible ( so that we can enhance the pymks  by adding new features-like CLD or Bayesian stuff-  and new notebooks).  Also, we would get closer to start working on the paper we were discussing.
 
@wd15,  What are the important steps  (issues) missing that are required for the next release? I think if we can prioritize them and assign them to specific people we can get things done faster. This is what I am thinking. What are your (@wd15, @auag92 ) thoughts on that?

@auag92, do you need any help on # 421?

**Comment by wd15** [comment]
Everything we need to do for the next release in this [the 0.4 milestone](https://github.com/materialsinnovation/pymks/milestone/7). Remove things that you think might be unnecessary.

**Comment by beyucel** [comment]
Sounds good!

Once we add everyone as a collaborator , we can split the issues and get it done. 
Thanks @wd15 !

**Comment by wd15** [comment]
I'll remove this comptelelty after released 0.4.1
