### ISSUE TITLE
TwoPointCorrelation or two_point_stats() returns incorrect dimensions for non-square input images

### ISSUE THREAD

**Issue by Nimal136** [materialsinnovation/pymks#562]
Hi PyMKS Team,

I have used 0.3.4 version in the past and recently upgraded to the re-written 0.4.1. Looks like the new versions can't handle images that are not square. e.g. I have an image that is (1000,1732) but stats returned are (999,999).
Also, the correlation stats are one pixel less than the input image in each dimension even if I set the cutoff is set to None. e.g. For a square image of shape (1000,1000), stats returned are (999,999). Please let me know if I am missing something here. 

I guess this has to do with how cutoff is implemented in two_point_stats() function.  I don't have a lot of experience with python decorators and so not sure how to modify the implementation to handle images of any size like in 0.3.4. Could you please help me with what I need to change? 

Cheers

**Comment by wd15** [comment]
@Nimal136 thanks for raising this issue. It seems we've certainly overlooked some shape issues in the latest releases. I'm working on fixing this so that the returned arrays make more sense. It should take a day or two to have something working. However, I'm still planning on returning a slightly different shape in the event of an even shaped axis. For example, for a 1D microstructure with two phases and 1 sample with only two cells. The array looks lke,

    [[0, 1]]

for example. Now, the current code for correlation [0, 0] will give

    [[0.5]]

The old code would give

    [[0, 0.5]]

I'm proposing to return

    [[0, 0.5, 0]]

The way we currently have it set up is that we lose one cell of information, which is not good. However it is nice to have the volume fraction value at the center of the domain. So, an nxn microstruture will return an (n+1)x(n+1) correlation. I think that makes sense.

Also, will fix the case when the microstructures don't have equal sides.

Once again, thanks for raising this. It's so helpful to have this kind of feedback.

**Comment by wd15** [comment]
@Nimal136, please see PR #566. This should address all the issues that you raised. If you'd like you can try that PR directly or wait for it to be merged.

**Comment by Nimal136** [comment]
@wd15  Thanks for looking into the issue. I have reverted to 0.3.4 for now to use my existing workflow. I will wait for this to be merged with the next stable release before trying it out. Acceleration using dask in 0.4.x is interesting. So will migrate to it at a later date.
